/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.89.1
  Forc version: 0.60.0
  Fuel-Core version: 0.27.0
*/

export type { OrderbookAbi } from './OrderbookAbi';

export { OrderbookAbi__factory } from './factories/OrderbookAbi__factory';
